#!/bin/bash
        
export GOOS=linux
export GOARCH=amd64

go build -ldflags "-w -s -X main.clientId=$CLIENT_ID \
-X main.clientSecret=$CLIENT_SECRET \
-X main.tokenFilename=gdrive_v2.json" \
-o gdrive

#export GOARCH=arm
#export BIN_NAME="gdrive_linux_rpi"
#export BIN_PATH="./bin"
#go build -ldflags '-w -s' -o ${BIN_PATH}/${BIN_NAME}

